### ISSUE TITLE
It won't work if you don't "Unblock" it from file properties.

### ISSUE THREAD

**Issue by OmarNamis** [matafokka/ExcelDarkThemeFix#1]
At first, I tried to use it and I followed all the steps but it didn't work.

Then, I checked the file properties of ExcelDarkThemeFix.xlam and noticed this message:
![Screenshot](https://user-images.githubusercontent.com/14346945/91717481-e69c2700-eb91-11ea-923a-f3f636203d08.png)
So I checked the "Unblock" checkbox then pressed ok, and now it works! 

You should update the README to let users know about this.

**Comment by matafokka** [comment]
Thank you for mentioning it! I completely forgot about it because I configured Excel not to block any files.
I've updated ReadMe with all necessary instructions.
