### ISSUE TITLE
Word version

### ISSUE THREAD

**Issue by matte22ladde** [matafokka/ExcelDarkThemeFix#11]
**Question itself**
A custom msstyle may randomly change the text color to white when the file is opened on other year edition of Word which basically makes them invisible. Hopefully there will be an add-in to force #ffffff as the background color and #00000 as the default font color when Word follows the system theme and saves the document. Ideally both in typing mode and print preview.

**Comment by matafokka** [comment]
Hi, thanks for reporting this! I thought MS fixed Word years ago.

Currently I'm working on 3 projects in my spare time, I'm not sure when I'll be able to make a fix for the Word.

In the meantime, can you send your Word build number?

You can see that by opening Word, clicking on "Account" and looking at "About Word" section:

![image](https://github.com/matafokka/ExcelDarkThemeFix/assets/34414488/23e379f2-42f8-482a-a1bb-4a89703b5bea)

**Comment by matafokka** [comment]
Hi! Sorry for making you wait so long. So, there's no reliable way to detect automatic font (and, possibly, background) color which is half the fix. I won't release and promote half-baked software. However, I'm [attaching](https://github.com/user-attachments/files/15945505/WordDarkThemeFix.zip) whatever I did, maybe someone will find that helpful. The code is basically ExcelDarkThemeFix but stripped down and changed to work with the Word.
