### ISSUE TITLE
Text is unreadable when the second color of the theme colors is set

### ISSUE THREAD

**Issue by 0xdeadc0d3** [matafokka/ExcelDarkThemeFix#13]
**Describe the bug**
Text is unreadable when the second color of the theme colors is set

**To Reproduce**
1. Create a workbook on a machine without a custom Windows dark theme and the Add-In installed
2. Intentionally set the font color to the second color of the theme colors (It is automatically set for the A1 cell)
3. Open the workbook on a machine with a custom Windows dark theme and the Add-In installed

**Screenshots**
![image](https://github.com/user-attachments/assets/cb386307-0f1d-4d13-abce-d9e263b8f77e)
![image](https://github.com/user-attachments/assets/0fd48a5a-3bc1-4f44-8031-babd281319ff)
![image](https://github.com/user-attachments/assets/b1a5cc29-9844-452e-a648-e42268670efc)

**Used software:**
1. Microsoft® Excel® LTSC MSO (Version 2407 Build 16.0.17830.20166) 64-bit 
2. Are there any installed Add-Ins or scripts in the workbook? - **No**

**Proposed solution**
Restore the original color palette with
```basic
Wb.Theme.ThemeColorScheme.Colors(msoThemeDark1) = vbBlack
Wb.Theme.ThemeColorScheme.Colors(msoThemeLight1) = vbWhite
```

**Comment by matafokka** [comment]
Приветствую, огромное спасибо! You've done a great work, I implemented your solution as an unsafe option because it'll break workbooks with overridden theme. I suggest finding another theme instead of using this option.

I was able to reproduce incorrect color palette, but unable to get incorrect cells colors with my set of themes installed. What Windows theme are you using?

**Comment by 0xdeadc0d3** [comment]
> What Windows theme are you using?

Rectify 11 Dark theme with Mica

**Comment by matafokka** [comment]
Thanks! I installed theme from Rectify 11 and still couldn't reproduce. I'll play with it when I'll have a bit more spare time.
