### ISSUE TITLE
Any update on Word version?

### ISSUE THREAD

**Issue by munish30monga** [matafokka/ExcelDarkThemeFix#14]
Hi, 

Both excel and powerpoint versions are extremely useful, I use them extensively on custom W11 dark themes. Please consider releasing a fix for Word, if possible. Thank you for your great work!

**Comment by matafokka** [comment]
Hello, thanks for the kind words! Unfortunately, Word fix is not possible, see details here: https://github.com/matafokka/ExcelDarkThemeFix/issues/11#issuecomment-2185251923
