### ISSUE TITLE
Libre Office compatibility

### ISSUE THREAD

**Issue by Leoxur** [matafokka/ExcelDarkThemeFix#3]
![Screenshot (10)](https://user-images.githubusercontent.com/9626769/100530832-6bc9c300-31f7-11eb-8f46-f40873ec7efa.png)
![Screenshot (8)](https://user-images.githubusercontent.com/9626769/100530834-6c625980-31f7-11eb-831c-083adc5aa9e1.png)

**Comment by matafokka** [comment]
Hello, ExcelDarkTheme is not compatible, is not intended to be compatible and will never be compatible with LibreOffice.

However, if you or somebody else are willing to fork and adapt my code to run in LibreOffice, I will be more than happy to support your work, though likely I won't participate in actual coding.

Some explanations regarding LibreOffice:

Firstly, your screenshots shows default LibreOffice behavior. As far as I've tested (not much), systems colors affects only graphic items in LibreOffice, everything else (sheet background, text color, etc) works fine.

Secondly, using my instructions, ExcelDarkThemeFix won't even run (and doesn't run in your case) in LibreOffice. Even though LibreOffice respects XLSTART content, it simply can't open .xlam files:
![image](https://user-images.githubusercontent.com/34414488/100541989-90a25280-3258-11eb-8076-f75048fdc546.png)

So you'll need to copy code from Excel modules to LibreOffice modules.

Thirdly, even after that script won't run without some changes. I just tried to copy my code and LibreOffice can't even compile it.
