### ISSUE TITLE
Reverts to theme color when editing a cell

### ISSUE THREAD

**Issue by smuun** [matafokka/ExcelDarkThemeFix#4]
**Describe the bug**
The cell I am currently editing reverts to theme color, and switches back to white after hitting enter.
Not a major issue at all.

**My configuration**
- Windows 10 build 19042.685
- niivu's nord theme
- ExcelDarkThemeFix applied using the hard method (easy method gave an error on startup)

**To Reproduce**
Steps to reproduce the behavior or link to the problematic workbook (or a part of it)
Open a workbook and edit a cell.

**Screenshots**
![image](https://user-images.githubusercontent.com/72632230/102386672-a3928200-3fcf-11eb-8726-771ec11bfa4a.png)

**Used software:**
1. MS Office version.
Office 365.

2. Are there any installed Add-Ins or scripts in the workbook?
No.

**Comment by smuun** [comment]
Just saw the mention of this in the readme--sorry :)

**Comment by matafokka** [comment]
Hello, glad you've figured this out :)

Be careful with this option though, you won't be able to undo changes done to the file. The only way to undo is to close the file without saving and open it again.

Unfortunately, it can't be fixed since changes made by scripts can't be undone, Excel doesn't track them.

**Comment by matafokka** [comment]
Oh, by the way, can you confirm that this script is completely compatible with Office 365, so I can safely mention it in readme?

**Comment by smuun** [comment]
Thanks for the warning!  I just decided to leave it disabled, it doesn't really bother me.

As far as office 365 compatibility, the quick install method does not work, but the longer one does.
Graphs don't seem to be fixed:
![image](https://user-images.githubusercontent.com/72632230/102405492-87034380-3fe9-11eb-9d30-8f510c0f6c1b.png)

and neither do styles (but they do show up correctly on the page):
![image](https://user-images.githubusercontent.com/72632230/102405843-fed16e00-3fe9-11eb-9cf4-0a44da854f83.png)

Let me know if you want help testing with 365.  I have a bit of experience writing VSTO add-ins (word), so I might be able to help with debugging.

**Comment by matafokka** [comment]
Thank you for the report and offer, I really appreciate it!

Seems like I'll have to install Office 365 :D

As for debugging, honestly, I don't know. Bugs are usually related to messed up API, so one needs to go deeply into docs, waste a lot of time on reading, etc. So it's easier to fix the bug yourself after all of this. I'll greatly appreciate it if you'll do the coding.

But anyway, huge thanks for the offer!

Edit: Misclicked and reopened issue, sorry!
