### ISSUE TITLE
Outlook version

### ISSUE THREAD

**Issue by Reabstraction** [matafokka/ExcelDarkThemeFix#9]
Many Outlook emails look broken, so would be nice if it were fixed

**Comment by matafokka** [comment]
Hi! Thanks for letting me know, I'll be sure to check it out and see what I can do.

**Comment by matafokka** [comment]
Hello again! Sorry for the delay.

Everything looks right to me. In the example below I'm using Outlook 2021 and BIB Night theme.

Browser (gmail):

![image](https://github.com/matafokka/ExcelDarkThemeFix/assets/34414488/4177db0b-5855-436c-a5b8-3ae37e306868)

Outlook with a dark theme:

![image](https://github.com/matafokka/ExcelDarkThemeFix/assets/34414488/f78f3f65-0ba4-4add-bc9c-79b761ad3888)

Outlook with a light theme:

![image](https://github.com/matafokka/ExcelDarkThemeFix/assets/34414488/b8922ec6-7e87-4f23-b8fd-dce82dd2d026)

Can you send me a problematic message to this address: `vjhnadfkljvghfjkadl@outlook.com`?

**Comment by matafokka** [comment]
Hi! I guess, I can close this issue because there's no response in 5 months, and the issue itself is not about Excel?

If you still wanna talk about Outlook, feel free to reopen this issue or [contact me on DeviantArt](https://www.deviantart.com/matafokka).
